// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: Protos/messages.proto

package Client_Server_Token_Manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stamp uint64 `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *CreateToken) Reset() {
	*x = CreateToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToken) ProtoMessage() {}

func (x *CreateToken) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToken.ProtoReflect.Descriptor instead.
func (*CreateToken) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateToken) GetStamp() uint64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

type DropToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stamp uint64 `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *DropToken) Reset() {
	*x = DropToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropToken) ProtoMessage() {}

func (x *DropToken) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropToken.ProtoReflect.Descriptor instead.
func (*DropToken) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DropToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DropToken) GetStamp() uint64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

type WriteToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low   uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid   uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High  uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Stamp uint64 `protobuf:"varint,6,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *WriteToken) Reset() {
	*x = WriteToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToken) ProtoMessage() {}

func (x *WriteToken) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToken.ProtoReflect.Descriptor instead.
func (*WriteToken) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{2}
}

func (x *WriteToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WriteToken) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *WriteToken) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *WriteToken) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *WriteToken) GetStamp() uint64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

type ReadToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stamp uint64 `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *ReadToken) Reset() {
	*x = ReadToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadToken) ProtoMessage() {}

func (x *ReadToken) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadToken.ProtoReflect.Descriptor instead.
func (*ReadToken) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ReadToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadToken) GetStamp() uint64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type CreateReplicateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *CreateReplicateResponse) Reset() {
	*x = CreateReplicateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplicateResponse) ProtoMessage() {}

func (x *CreateReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplicateResponse.ProtoReflect.Descriptor instead.
func (*CreateReplicateResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReplicateResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type DropResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *DropResponse) Reset() {
	*x = DropResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropResponse) ProtoMessage() {}

func (x *DropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropResponse.ProtoReflect.Descriptor instead.
func (*DropResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DropResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res uint64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{7}
}

func (x *WriteResponse) GetRes() uint64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type WriteReplicateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res uint64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *WriteReplicateResponse) Reset() {
	*x = WriteReplicateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReplicateResponse) ProtoMessage() {}

func (x *WriteReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReplicateResponse.ProtoReflect.Descriptor instead.
func (*WriteReplicateResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{8}
}

func (x *WriteReplicateResponse) GetRes() uint64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res uint64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReadResponse) GetRes() uint64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type ReadWriteToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadWriteToken) Reset() {
	*x = ReadWriteToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWriteToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteToken) ProtoMessage() {}

func (x *ReadWriteToken) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteToken.ProtoReflect.Descriptor instead.
func (*ReadWriteToken) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ReadWriteToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low          uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid          uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High         uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Stamp        uint64 `protobuf:"varint,6,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Partialvalue uint64 `protobuf:"varint,7,opt,name=partialvalue,proto3" json:"partialvalue,omitempty"`
	Finalvalue   uint64 `protobuf:"varint,8,opt,name=finalvalue,proto3" json:"finalvalue,omitempty"`
}

func (x *ReadWriteResponse) Reset() {
	*x = ReadWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWriteResponse) ProtoMessage() {}

func (x *ReadWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWriteResponse.ProtoReflect.Descriptor instead.
func (*ReadWriteResponse) Descriptor() ([]byte, []int) {
	return file_Protos_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ReadWriteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadWriteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadWriteResponse) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ReadWriteResponse) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ReadWriteResponse) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ReadWriteResponse) GetStamp() uint64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

func (x *ReadWriteResponse) GetPartialvalue() uint64 {
	if x != nil {
		return x.Partialvalue
	}
	return 0
}

func (x *ReadWriteResponse) GetFinalvalue() uint64 {
	if x != nil {
		return x.Finalvalue
	}
	return 0
}

var File_Protos_messages_proto protoreflect.FileDescriptor

var file_Protos_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0x33, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x31, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x7e, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x31, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x23, 0x0a, 0x0f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22,
	0x2d, 0x0a, 0x19, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x21,
	0x0a, 0x0d, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65,
	0x73, 0x22, 0x22, 0x0a, 0x0e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x18, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xcb, 0x01, 0x0a, 0x13, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xdb, 0x03, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4d, 0x67, 0x6d, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x17, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x72,
	0x6f, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3c, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x1a, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x1a, 0x21, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x20, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x16, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x1b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x69, 0x72, 0x75, 0x64, 0x68, 0x62, 0x6d, 0x31, 0x31, 0x2f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x2d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Protos_messages_proto_rawDescOnce sync.Once
	file_Protos_messages_proto_rawDescData = file_Protos_messages_proto_rawDesc
)

func file_Protos_messages_proto_rawDescGZIP() []byte {
	file_Protos_messages_proto_rawDescOnce.Do(func() {
		file_Protos_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protos_messages_proto_rawDescData)
	})
	return file_Protos_messages_proto_rawDescData
}

var file_Protos_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_Protos_messages_proto_goTypes = []interface{}{
	(*CreateToken)(nil),             // 0: Protos.CreateToken
	(*DropToken)(nil),               // 1: Protos.DropToken
	(*WriteToken)(nil),              // 2: Protos.WriteToken
	(*ReadToken)(nil),               // 3: Protos.ReadToken
	(*CreateResponse)(nil),          // 4: Protos.create_response
	(*CreateReplicateResponse)(nil), // 5: Protos.create_replicate_response
	(*DropResponse)(nil),            // 6: Protos.drop_response
	(*WriteResponse)(nil),           // 7: Protos.write_response
	(*WriteReplicateResponse)(nil),  // 8: Protos.write_replicate_response
	(*ReadResponse)(nil),            // 9: Protos.read_response
	(*ReadWriteToken)(nil),          // 10: Protos.ReadWriteToken
	(*ReadWriteResponse)(nil),       // 11: Protos.read_write_response
}
var file_Protos_messages_proto_depIdxs = []int32{
	0,  // 0: Protos.TokenMgmt.CreateRequest:input_type -> Protos.CreateToken
	1,  // 1: Protos.TokenMgmt.DropRequest:input_type -> Protos.DropToken
	2,  // 2: Protos.TokenMgmt.WriteRequest:input_type -> Protos.WriteToken
	3,  // 3: Protos.TokenMgmt.ReadRequest:input_type -> Protos.ReadToken
	0,  // 4: Protos.TokenMgmt.CreateReplicate:input_type -> Protos.CreateToken
	2,  // 5: Protos.TokenMgmt.WriteReplicate:input_type -> Protos.WriteToken
	10, // 6: Protos.TokenMgmt.ReadWrite:input_type -> Protos.ReadWriteToken
	4,  // 7: Protos.TokenMgmt.CreateRequest:output_type -> Protos.create_response
	6,  // 8: Protos.TokenMgmt.DropRequest:output_type -> Protos.drop_response
	7,  // 9: Protos.TokenMgmt.WriteRequest:output_type -> Protos.write_response
	9,  // 10: Protos.TokenMgmt.ReadRequest:output_type -> Protos.read_response
	5,  // 11: Protos.TokenMgmt.CreateReplicate:output_type -> Protos.create_replicate_response
	8,  // 12: Protos.TokenMgmt.WriteReplicate:output_type -> Protos.write_replicate_response
	11, // 13: Protos.TokenMgmt.ReadWrite:output_type -> Protos.read_write_response
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_Protos_messages_proto_init() }
func file_Protos_messages_proto_init() {
	if File_Protos_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protos_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReplicateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteReplicateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWriteToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protos_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protos_messages_proto_goTypes,
		DependencyIndexes: file_Protos_messages_proto_depIdxs,
		MessageInfos:      file_Protos_messages_proto_msgTypes,
	}.Build()
	File_Protos_messages_proto = out.File
	file_Protos_messages_proto_rawDesc = nil
	file_Protos_messages_proto_goTypes = nil
	file_Protos_messages_proto_depIdxs = nil
}
